baseurl = "https://chipsenkbeil.com/"
theme = "coder"
languageCode = "en-us"

[params]
    author = "Chip Senkbeil"
    info = "Solutions Engineer @ Facebook"
    description = "Chip Senkbeil's Personal Website"
    keywords = "blog,developer,personal"

[[params.social]]
    name = "github"
    weight = 1
    url = "https://github.com/chipsenkbeil/"
[[params.social]]
    name = "twitter"
    weight = 2
    url = "https://twitter.com/chipsenkbeil/"
[[params.social]]
    name = "linkedin"
    weight = 3
    url = "https://linkedin.com/in/robertsenkbeil/"

[[menu.main]]
    name = "Blog"
    weight = 1
    url = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"

