# Site settings
baseurl = "http://senkbeil.org/"
languageCode = "en-us"
title = "Senkbeil"
theme = "grid-side"
copyright = "Copyright &#169; by Chip Senkbeil"
SectionPagesMenu = "main"
paginate = 12
PygmentsCodeFences = true

[[menu.main]]
    name = "about hugo"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"
[[menu.main]]
    name = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/getting-started/"
[[menu.main]]
    name = "a"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/getting-started/"
[[menu.main]]
    parent = "getting started"
    name = "about hugo 2"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about/"
[[menu.main]]
    parent = "about hugo"
    name = "getting started 2"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/getting-started/"

[Params]

    #
    # Provide your name, description, and email that you want to include on
    # the main image of the main page.
    #
    name = "Your name"
    description = "Your description"
    email = "your@email.com"

    [Params.Highlight]

        style = "railscasts"

    #
    # Contains the main grid cell of your site (such as a picture of yourself)
    # along with your name, description, and email. Any empty field will
    # not be included. Not providing an image will use a color. Marking as
    # disabled results in this cell not appearing in the site.
    #
    [Params.Header]

        name = "Chip Senkbeil"
        description = "Computer Engineer/Scientist/Maniac"
        email = "chip.senkbeil@gmail.com"
        image = "/img/profile.jpg"
        image_position = "top"
        #color = "#FFF"

    [Params.Footer]

        name = "Chip Senkbeil"

        [[Params.Footer.List]]

            icon_class = "twitter"
            icon_link = "https://twitter.com/ChipSenkbeil"

        [[Params.Footer.List]]

            icon_class = "linkedin"
            icon_link = "https://www.linkedin.com/in/robertsenkbeil"

        [[Params.Footer.List]]

            icon_class = "google-plus"
            icon_link = "https://www.google.com/+ChipSenkbeil"

        [[Params.Footer.List]]

            icon_class = "github"
            icon_link = "https://www.github.com/rcsenkbeil"

    #
    # Contains the Cells representing the sections of your website. Each cell
    # contains the name of the cell, a brief description, and a link to the
    # associated section. 
    #
    # Not providing an image will use the color specified by 'color' as the
    # background color (default to #FFF).
    #
    # You can embed an icon using 'icon' to specify the classes to use
    # for the icon (such as 'fa fa-flag' when using font awesome).
    #
    # By default, each cell has a grid size of 1/3 (4 out of 12) for large
    # screens, 1/2 (6 out of 12) for medium screens, and 1 (12 out of 12) for
    # small screens. To change the cell's size per screen, use the properties
    # 'cell_large', 'cell_medium', and 'cell_small' respectively with a number
    # ranging from 1 to 12. Make sure that Cells have nubmers equalling 12
    # per row.
    #
    [Params.Cells]

        [[Params.Cells.List]]

            name = "Blog"
            description = "Your personal blog"
            link = "/post/"
            image = "/img/tmp/car.jpg"

        [[Params.Cells.List]]

            name = "Super Mega Awesometastic Feature of the Week"
            description = ""
            link = ""
            image = "/img/tmp/cup.jpg"

        [[Params.Cells.List]]

            name = "Something on only two lines"
            description = ""
            link = ""
            image = "/img/tmp/drone.jpg"

        [[Params.Cells.List]]

            name = ""
            description = ""
            link = ""
            image = "/img/tmp/food.jpg"

        [[Params.Cells.List]]

            name = ""
            description = ""
            link = ""
            image = "/img/tmp/jars.jpg"

        [[Params.Cells.List]]

            name = ""
            description = ""
            link = ""
            image = "/img/tmp/phone.jpg"

        [[Params.Cells.List]]

            name = "Something"
            description = ""
            link = ""
            image = "/img/tmp/poster.jpg"

