baseurl = "https://chipsenkbeil.com/"
title = "Chip Senkbeil"

theme = "coder"
languageCode = "en-us"

paginate = 12
canonifyurls = true

# pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses=true

googleAnalytics = "UA-71733200-2"

# Disable disqus as I'll take comments via Twitter or other mediums
# disqusShortname = "chipsenkbeil"

[params]
    author = "Chip Senkbeil"
    info = "Solutions Engineer @ Facebook"
    description = "Chip Senkbeil's Personal Website"
    keywords = "blog,developer,personal"
    hideCredits = true
    footercontent = "Views are my own<br /><a href=\"/keys/chipsenkbeil.pub.gpg\">Public Keys</a>"
    avatarurl = "/img/profile.jpg"
    custom_css = ["/styles/gruvbox.css"]
    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

[[params.social]]
    name = "github"
    weight = 1
    url = "https://github.com/chipsenkbeil/"
[[params.social]]
    name = "twitter"
    weight = 2
    url = "https://twitter.com/chipsenkbeil/"
[[params.social]]
    name = "linkedin"
    weight = 3
    url = "https://linkedin.com/in/robertsenkbeil/"
[[params.social]]
    name = "keybase"
    weight = 4
    url = "https://keybase.io/senkwich"

[[menu.main]]
    name = "blog"
    weight = 1
    url = "/posts/"
[[menu.main]]
    name = "notes"
    weight = 2
    url = "/notes/"
[[menu.main]]
    name = "reading"
    weight = 3
    url = "/reading/"
[[menu.main]]
    name = "about"
    weight = 4
    url = "/about/"
