# Site settings
baseurl = "http://chipsenkbeil.com/"
languageCode = "en-us"
title = "Senkbeil"
theme = "grid-side"
copyright = "Copyright &#169; by Chip Senkbeil"
paginate = 12
disqusShortname = "chipsenkbeil"

# About section of menu
[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "#!"

[[Menu.Main]]
    name = "Pepper"
    identifier = "pepper"
    url = "pepper/"
    parent = "about"

[[Menu.Main]]
    name = "Resume"
    identifier = "resume"
    url = "resume/"
    parent = "about"

# Blog section of menu
[[Menu.Main]]
    name = "Blog"
    identifier = "blog"
    url = "#!"

[[Menu.Main]]
    name = "Posts"
    identifier = "posts"
    url = "post/"
    parent = "blog"

[[Menu.Main]]
    name = "Talks"
    identifier = "talks"
    url = "talk/"
    parent = "blog"

[[Menu.Main]]
    name = "Notes"
    identifier = "notes"
    url = "note/"
    parent = "blog"

[[Menu.Main]]
    name = "Snippets"
    identifier = "snippets"
    url = "#!"
    parent = "blog"

# Projects section of menu
[[Menu.Main]]
    name = "Projects"
    identifier = "projects"
    url = "#!"

[[Menu.Main]]
    name = "Software"
    identifier = "software"
    url = "software/"
    parent = "projects"

[[Menu.Main]]
    name = "Hardware"
    identifier = "hardware"
    url = "#!"
    parent = "projects"


[Params]

    infinite_scroll = true

    [Params.Highlight]

        style = "railscasts"

    [Params.Header]

        name = "Chip Senkbeil"
        description = "Computer Engineer/Scientist/Maniac"
        email = "chip.senkbeil@gmail.com"
        image = "img/profile.jpg"
        image_position = "top"

    [Params.Footer]

        name = "Chip Senkbeil"

        [[Params.Footer.List]]

            icon_class = "twitter"
            icon_link = "https://twitter.com/ChipSenkbeil"

        [[Params.Footer.List]]

            icon_class = "linkedin"
            icon_link = "https://www.linkedin.com/in/robertsenkbeil"

        [[Params.Footer.List]]

            icon_class = "google-plus"
            icon_link = "https://www.google.com/+ChipSenkbeil"

        [[Params.Footer.List]]

            icon_class = "github"
            icon_link = "https://www.github.com/chipsenkbeil"

    [Params.Cells]

        [[Params.Cells.List]]

            name = "Blog"
            link = "post/"
            image = "img/blog.jpg"

        [[Params.Cells.List]]

            name = "Resumé"
            link = "resume/"
            image = "img/resume.jpg"

        [[Params.Cells.List]]

            name = "Software"
            link = "software/"
            image = "img/software.jpg"

        [[Params.Cells.List]]

            name = "Hardware"
            link = "hardware/"
            image = "img/hardware.jpg"
            disable = true

        [[Params.Cells.List]]

            name = "Talks"
            link = "talk/"
            image = "img/talk.jpg"
            image_position = "center"

        [[Params.Cells.List]]

            name = "Pepper"
            link = "pepper/"
            image = "img/pepper.jpg"
            image_position = "top"

        [[Params.Cells.List]]

            name = "Snippets"
            link = "snippet/"
            image = "img/snippet.jpg"
            disable = true

        [[Params.Cells.List]]

            name = "Notes"
            link = "note/"
            image = "img/note.jpg"

