#
# Theme and general site configuration
#

baseURL = "https://chipsenkbeil.com/"
title = "Chip Senkbeil"
theme = "hugo-coder"
languageCode = "en-us"
defaultContentLanguage = "en"
enableEmoji = true
timeZone = "America/Chicago"

# TODO: This is a legacy option that will be removed, so need
#       to look into how to replcae this in the future!
canonifyurls = true

#
# PAGINATION (MAX ARTICLES PER PAGE)
#

[pagination]
    pagerSize = 12

#
# SYNTAX HIGHLIGHTING
#

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        noClasses = false
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

#
# TAXONOMIES
#

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
    author = "authors"

#
# THEME CONFIGURATION
#

[params]
    author = "Chip Senkbeil"
    info = "Staff Business Engineer @ Meta"
    description = "Chip Senkbeil's Personal Website"
    keywords = "blog,developer,personal"

    avatarurl = "/img/profile.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    since = 2012

    # Configure color scheme to be automatic to match system setting
    # of light vs dark. We also disable JavaScript (including coder.js)
    # as we want a pure static site without JavaScript; this means that
    # we also need to set hiding the color scheme toggle to true as that
    # is only available when JavaScript is included, which we don't want!
    colorScheme = "auto"
    hideColorSchemeToggle = true
    disableDefaultJsScripts = true

#
# THEME SOCIAL CONFIGURATION FOR MAIN PAGE
#

[[params.social]]
    name = "email"
    weight = 1
    url = "mailto:mail@chipsenkbeil.com"
[[params.social]]
    name = "github"
    weight = 2
    url = "https://github.com/chipsenkbeil/"
[[params.social]]
    name = "twitter"
    weight = 3
    url = "https://twitter.com/chipsenkbeil/"
[[params.social]]
    name = "linkedin"
    weight = 4
    url = "https://linkedin.com/in/robertsenkbeil/"
[[params.social]]
    name = "keybase"
    weight = 5
    url = "https://keybase.io/senkwich"

#
# THEME MENU STRUCTURE ACROSS WEBSITE
#

[[menu.main]]
    name = "blog"
    weight = 1
    url = "/posts/"
[[menu.main]]
    name = "notes"
    weight = 2
    url = "/notes/"
[[menu.main]]
    name = "miscellaneous"
    weight = 3
    url = "/miscellaneous/"
[[menu.main]]
    name = "about"
    weight = 4
    url = "/about/"
